
<input type="hidden" name="nomeArmazem" value="<?php echo $nomeArmazem; ?>">
<input type="hidden" name="armazenamentoRecintoAduaneiroCodigo" value="<?php echo $armazenamentoRecintoAduaneiroCodigo; ?>">
<input type="hidden" name="armazenamentoRecintoAduaneiroNome" value="<?php echo $armazenamentoRecintoAduaneiroNome; ?>">
<input type="hidden" name="armazenamentoSetor" value="<?php echo $armazenamentoSetor; ?>">
<input type="hidden" name="canalSelecaoParametrizada" value="<?php echo $canalSelecaoParametrizada; ?>">
<input type="hidden" name="caracterizacaoOperacaoCodigoTipo" value="<?php echo $caracterizacaoOperacaoCodigoTipo; ?>">
<input type="hidden" name="caracterizacaoOperacaoDescricaoTipo" value="<?php echo $caracterizacaoOperacaoDescricaoTipo; ?>">
<input type="hidden" name="cargaDataChegada" value="<?php echo $cargaDataChegada; ?>">
<input type="hidden" name="cargaNumeroAgente" value="<?php echo $cargaNumeroAgente; ?>">
<input type="hidden" name="cargaPaisProcedenciaCodigo" value="<?php echo $cargaPaisProcedenciaCodigo; ?>">
<input type="hidden" name="cargaPaisProcedenciaNome" value="<?php echo $cargaPaisProcedenciaNome; ?>">
<input type="hidden" name="cargaPesoBruto" value="<?php echo $cargaPesoBruto; ?>">
<input type="hidden" name="cargaPesoLiquido" value="<?php echo $cargaPesoLiquido; ?>">
<input type="hidden" name="cargaUrfEntradaCodigo" value="<?php echo $cargaUrfEntradaCodigo; ?>">
<input type="hidden" name="cargaUrfEntradaNome" value="<?php echo $cargaUrfEntradaNome; ?>">
<input type="hidden" name="conhecimentoCargaEmbarqueData" value="<?php echo $conhecimentoCargaEmbarqueData; ?>">
<input type="hidden" name="conhecimentoCargaEmbarqueLocal" value="<?php echo $conhecimentoCargaEmbarqueLocal; ?>">
<input type="hidden" name="conhecimentoCargaId" value="<?php echo $conhecimentoCargaId; ?>">
<input type="hidden" name="conhecimentoCargaTipoCodigo" value="<?php echo $conhecimentoCargaTipoCodigo; ?>">
<input type="hidden" name="conhecimentoCargaTipoNome" value="<?php echo $conhecimentoCargaTipoNome; ?>">
<input type="hidden" name="conhecimentoCargaUtilizacao" value="<?php echo $conhecimentoCargaUtilizacao; ?>">
<input type="hidden" name="conhecimentoCargaUtilizacaoNome" value="<?php echo $conhecimentoCargaUtilizacaoNome; ?>">
<input type="hidden" name="dataDesembaraco" value="<?php echo $dataDesembaraco; ?>">
<input type="hidden" name="dataRegistro" value="<?php echo $dataRegistro; ?>">
<input type="hidden" name="documentoChegadaCargaCodigoTipo" value="<?php echo $documentoChegadaCargaCodigoTipo; ?>">
<input type="hidden" name="documentoChegadaCargaNome" value="<?php echo $documentoChegadaCargaNome; ?>">
<input type="hidden" name="documentoChegadaCargaNumero" value="<?php echo $documentoChegadaCargaNumero; ?>">
<input type="hidden" name="codigoTipoDocumentoDespacho0" value="<?php echo $codigoTipoDocumentoDespacho0; ?>">
<input type="hidden" name="nomeDocumentoDespacho0" value="<?php echo $nomeDocumentoDespacho0; ?>">
<input type="hidden" name="numeroDocumentoDespacho0" value="<?php echo $numeroDocumentoDespacho0; ?>">
<input type="hidden" name="codigoTipoDocumentoDespacho1" value="<?php echo $codigoTipoDocumentoDespacho1; ?>">
<input type="hidden" name="nomeDocumentoDespacho1" value="<?php echo $nomeDocumentoDespacho1; ?>">
<input type="hidden" name="numeroDocumentoDespacho1" value="<?php echo $numeroDocumentoDespacho1; ?>">
<input type="hidden" name="codigoTipoDocumentoDespacho2" value="<?php echo $codigoTipoDocumentoDespacho2; ?>">
<input type="hidden" name="nomeDocumentoDespacho2" value="<?php echo $nomeDocumentoDespacho2; ?>">
<input type="hidden" name="numeroDocumentoDespacho2" value="<?php echo $numeroDocumentoDespacho2; ?>">
<input type="hidden" name="dossieDataVinculacao" value="<?php echo $dossieDataVinculacao; ?>">
<input type="hidden" name="dossieHoraVinculacao" value="<?php echo $dossieHoraVinculacao; ?>">
<input type="hidden" name="dossieNumero" value="<?php echo $dossieNumero; ?>">
<input type="hidden" name="indicadorDossieVazio" value="<?php echo $indicadorDossieVazio; ?>">
<input type="hidden" name="codigoTipoEmbalagem" value="<?php echo $codigoTipoEmbalagem; ?>">
<input type="hidden" name="nomeEmbalagem" value="<?php echo $nomeEmbalagem; ?>">
<input type="hidden" name="quantidadeVolume" value="<?php echo $quantidadeVolume; ?>">
<input type="hidden" name="freteCollect" value="<?php echo $freteCollect; ?>">
<input type="hidden" name="freteEmTerritorioNacional" value="<?php echo $freteEmTerritorioNacional; ?>">
<input type="hidden" name="freteMoedaNegociadaCodigo" value="<?php echo $freteMoedaNegociadaCodigo; ?>">
<input type="hidden" name="freteMoedaNegociadaNome" value="<?php echo $freteMoedaNegociadaNome; ?>">
<input type="hidden" name="fretePrepaid" value="<?php echo $fretePrepaid; ?>">
<input type="hidden" name="freteTotalDolares" value="<?php echo $freteTotalDolares; ?>">
<input type="hidden" name="freteTotalMoeda" value="<?php echo $freteTotalMoeda; ?>">
<input type="hidden" name="freteTotalReais" value="<?php echo $freteTotalReais; ?>">
<input type="hidden" name="agenciaIcms" value="<?php echo $agenciaIcms; ?>">
<input type="hidden" name="bancoIcms" value="<?php echo $bancoIcms; ?>">
<input type="hidden" name="codigoTipoRecolhimentoIcms" value="<?php echo $codigoTipoRecolhimentoIcms; ?>">
<input type="hidden" name="cpfResponsavelRegistro" value="<?php echo $cpfResponsavelRegistro; ?>">
<input type="hidden" name="dataPagamentoIcms" value="<?php echo $dataPagamentoIcms; ?>">
<input type="hidden" name="dataRegistro1" value="<?php echo $dataRegistro; ?>">
<input type="hidden" name="horaRegistro" value="<?php echo $horaRegistro; ?>">
<input type="hidden" name="nomeTipoRecolhimentoIcms" value="<?php echo $nomeTipoRecolhimentoIcms; ?>">
<input type="hidden" name="numeroSequencialIcms" value="<?php echo $numeroSequencialIcms; ?>">
<input type="hidden" name="ufIcms" value="<?php echo $ufIcms; ?>">
<input type="hidden" name="valorTotalIcms" value="<?php echo $valorTotalIcms; ?>">
<input type="hidden" name="importadorCodigoTipo" value="<?php echo $importadorCodigoTipo; ?>">
<input type="hidden" name="importadorCpfRepresentanteLegal" value="<?php echo $importadorCpfRepresentanteLegal; ?>">
<input type="hidden" name="importadorEnderecoBairro" value="<?php echo $importadorEnderecoBairro; ?>">
<input type="hidden" name="importadorEnderecoCep" value="<?php echo $importadorEnderecoCep; ?>">
<input type="hidden" name="importadorEnderecoLogradouro" value="<?php echo $importadorEnderecoLogradouro; ?>">
<input type="hidden" name="importadorEnderecoMunicipio" value="<?php echo $importadorEnderecoMunicipio; ?>">
<input type="hidden" name="importadorEnderecoNumero" value="<?php echo $importadorEnderecoNumero; ?>">
<input type="hidden" name="importadorEnderecoUf" value="<?php echo $importadorEnderecoUf; ?>">
<input type="hidden" name="importadorNome" value="<?php echo $importadorNome; ?>">
<input type="hidden" name="importadorNomeRepresentanteLegal" value="<?php echo $importadorNomeRepresentanteLegal; ?>">
<input type="hidden" name="importadorNumero" value="<?php echo $importadorNumero; ?>">
<input type="hidden" name="importadorNumeroTelefone" value="<?php echo $importadorNumeroTelefone; ?>">
<input type="hidden" name="informacaoComplementar" value="<?php echo $informacaoComplementar; ?>">
<input type="hidden" name="localDescargaTotalDolares" value="<?php echo $localDescargaTotalDolares; ?>">
<input type="hidden" name="localDescargaTotalReais" value="<?php echo $localDescargaTotalReais; ?>">
<input type="hidden" name="localEmbarqueTotalDolares" value="<?php echo $localEmbarqueTotalDolares; ?>">
<input type="hidden" name="localEmbarqueTotalReais" value="<?php echo $localEmbarqueTotalReais; ?>">
<input type="hidden" name="modalidadeDespachoCodigo" value="<?php echo $modalidadeDespachoCodigo; ?>">
<input type="hidden" name="modalidadeDespachoNome" value="<?php echo $modalidadeDespachoNome; ?>">
<input type="hidden" name="numeroDI" value="<?php echo $numeroDI; ?>">
<input type="hidden" name="operacaoFundap" value="<?php echo $operacaoFundap; ?>">
<input type="hidden" name="agenciaPagamento0" value="<?php echo $agenciaPagamento0; ?>">
<input type="hidden" name="bancoPagamento0" value="<?php echo $bancoPagamento0; ?>">
<input type="hidden" name="codigoReceita0" value="<?php echo $codigoReceita0; ?>">
<input type="hidden" name="codigoTipoPagamento0" value="<?php echo $codigoTipoPagamento0; ?>">
<input type="hidden" name="contaPagamento0" value="<?php echo $contaPagamento0; ?>">
<input type="hidden" name="dataPagamento0" value="<?php echo $dataPagamento0; ?>">
<input type="hidden" name="nomeTipoPagamento0" value="<?php echo $nomeTipoPagamento0; ?>">
<input type="hidden" name="numeroRetificacao0" value="<?php echo $numeroRetificacao0; ?>">
<input type="hidden" name="valorJurosEncargos0" value="<?php echo $valorJurosEncargos0; ?>">
<input type="hidden" name="valorMulta0" value="<?php echo $valorMulta0; ?>">
<input type="hidden" name="valorReceita0" value="<?php echo $valorReceita0; ?>">
<input type="hidden" name="agenciaPagamento1" value="<?php echo $agenciaPagamento1; ?>">
<input type="hidden" name="bancoPagamento1" value="<?php echo $bancoPagamento1; ?>">
<input type="hidden" name="codigoReceita1" value="<?php echo $codigoReceita1; ?>">
<input type="hidden" name="codigoTipoPagamento1" value="<?php echo $codigoTipoPagamento1; ?>">
<input type="hidden" name="contaPagamento1" value="<?php echo $contaPagamento1; ?>">
<input type="hidden" name="dataPagamento1" value="<?php echo $dataPagamento1; ?>">
<input type="hidden" name="nomeTipoPagamento1" value="<?php echo $nomeTipoPagamento1; ?>">
<input type="hidden" name="numeroRetificacao1" value="<?php echo $numeroRetificacao1; ?>">
<input type="hidden" name="valorJurosEncargos1" value="<?php echo $valorJurosEncargos1; ?>">
<input type="hidden" name="valorMulta1" value="<?php echo $valorMulta1; ?>">
<input type="hidden" name="valorReceita1" value="<?php echo $valorReceita1; ?>">
<input type="hidden" name="agenciaPagamento2" value="<?php echo $agenciaPagamento2; ?>">
<input type="hidden" name="bancoPagamento2" value="<?php echo $bancoPagamento2; ?>">
<input type="hidden" name="codigoReceita2" value="<?php echo $codigoReceita2; ?>">
<input type="hidden" name="codigoTipoPagamento2" value="<?php echo $codigoTipoPagamento2; ?>">
<input type="hidden" name="contaPagamento2" value="<?php echo $contaPagamento2; ?>">
<input type="hidden" name="dataPagamento2" value="<?php echo $dataPagamento2; ?>">
<input type="hidden" name="nomeTipoPagamento2" value="<?php echo $nomeTipoPagamento2; ?>">
<input type="hidden" name="numeroRetificacao2" value="<?php echo $numeroRetificacao2; ?>">
<input type="hidden" name="valorJurosEncargos2" value="<?php echo $valorJurosEncargos2; ?>">
<input type="hidden" name="valorMulta2" value="<?php echo $valorMulta2; ?>">
<input type="hidden" name="valorReceita2" value="<?php echo $valorReceita2; ?>">
<input type="hidden" name="agenciaPagamento3" value="<?php echo $agenciaPagamento3; ?>">
<input type="hidden" name="bancoPagamento3" value="<?php echo $bancoPagamento3; ?>">
<input type="hidden" name="codigoReceita3" value="<?php echo $codigoReceita3; ?>">
<input type="hidden" name="codigoTipoPagamento3" value="<?php echo $codigoTipoPagamento3; ?>">
<input type="hidden" name="contaPagamento3" value="<?php echo $contaPagamento3; ?>">
<input type="hidden" name="dataPagamento3" value="<?php echo $dataPagamento3; ?>">
<input type="hidden" name="nomeTipoPagamento3" value="<?php echo $nomeTipoPagamento3; ?>">
<input type="hidden" name="numeroRetificacao3" value="<?php echo $numeroRetificacao3; ?>">
<input type="hidden" name="valorJurosEncargos3" value="<?php echo $valorJurosEncargos3; ?>">
<input type="hidden" name="valorMulta3" value="<?php echo $valorMulta3; ?>">
<input type="hidden" name="valorReceita3" value="<?php echo $valorReceita3; ?>">
<input type="hidden" name="seguroMoedaNegociadaCodigo" value="<?php echo $seguroMoedaNegociadaCodigo; ?>">
<input type="hidden" name="seguroTotalDolares" value="<?php echo $seguroTotalDolares; ?>">
<input type="hidden" name="seguroTotalMoedaNegociada" value="<?php echo $seguroTotalMoedaNegociada; ?>">
<input type="hidden" name="seguroTotalReais" value="<?php echo $seguroTotalReais; ?>">
<input type="hidden" name="sequencialRetificacao" value="<?php echo $sequencialRetificacao; ?>">
<input type="hidden" name="situacaoEntregaCarga" value="<?php echo $situacaoEntregaCarga; ?>">
<input type="hidden" name="tipoDeclaracaoCodigo" value="<?php echo $tipoDeclaracaoCodigo; ?>">
<input type="hidden" name="tipoDeclaracaoNome" value="<?php echo $tipoDeclaracaoNome; ?>">
<input type="hidden" name="totalAdicoes" value="<?php echo $totalAdicoes; ?>">
<input type="hidden" name="urfDespachoCodigo" value="<?php echo $urfDespachoCodigo; ?>">
<input type="hidden" name="urfDespachoNome" value="<?php echo $urfDespachoNome; ?>">
<input type="hidden" name="valorTotalMultaARecolher" value="<?php echo $valorTotalMultaARecolher; ?>">
<input type="hidden" name="valorTotalMultaARecolherAjustado" value="<?php echo $valorTotalMultaARecolherAjustado; ?>">
<input type="hidden" name="viaTransporteCodigo" value="<?php echo $viaTransporteCodigo; ?>">
<input type="hidden" name="viaTransporteMultimodal" value="<?php echo $viaTransporteMultimodal; ?>">
<input type="hidden" name="viaTransporteNome" value="<?php echo $viaTransporteNome; ?>">
<input type="hidden" name="viaTransporteNomeTransportador" value="<?php echo $viaTransporteNomeTransportador; ?>">
<input type="hidden" name="viaTransportePaisTransportadorCodigo" value="<?php echo $viaTransportePaisTransportadorCodigo; ?>">
<input type="hidden" name="viaTransportePaisTransportadorNome" value="<?php echo $viaTransportePaisTransportadorNome; ?>">