
<?php
$nomeArmazem                        = " " . $declaracaoImportacao->armazem->nomeArmazem .  "";

$armazenamentoRecintoAduaneiroCodigo= " " . $declaracaoImportacao->armazenamentoRecintoAduaneiroCodigo .  "";
$armazenamentoRecintoAduaneiroNome  = " " . $declaracaoImportacao->armazenamentoRecintoAduaneiroNome .  "";
$armazenamentoSetor                 = " " . $declaracaoImportacao->armazenamentoSetor .  "";
$canalSelecaoParametrizada          = " " . $declaracaoImportacao->canalSelecaoParametrizada .  "";
$caracterizacaoOperacaoCodigoTipo   = " " . $declaracaoImportacao->caracterizacaoOperacaoCodigoTipo .  "";
$caracterizacaoOperacaoDescricaoTipo= " " . $declaracaoImportacao->caracterizacaoOperacaoDescricaoTipo .  "";
$cargaDataChegada                   = " " . $declaracaoImportacao->cargaDataChegada .  "";
$cargaNumeroAgente                  = " " . $declaracaoImportacao->cargaNumeroAgente .  "";
$cargaPaisProcedenciaCodigo         = " " . $declaracaoImportacao->cargaPaisProcedenciaCodigo .  "";
$cargaPaisProcedenciaNome           = " " . $declaracaoImportacao->cargaPaisProcedenciaNome .  "";
$cargaPesoBruto                     = " " . $declaracaoImportacao->cargaPesoBruto .  "";
$cargaPesoLiquido                   = " " . $declaracaoImportacao->cargaPesoLiquido .  "";
$cargaUrfEntradaCodigo              = " " . $declaracaoImportacao->cargaUrfEntradaCodigo .  "";
$cargaUrfEntradaNome                = " " . $declaracaoImportacao->cargaUrfEntradaNome .  "";
$conhecimentoCargaEmbarqueData      = " " . $declaracaoImportacao->conhecimentoCargaEmbarqueData .  "";
$conhecimentoCargaEmbarqueLocal     = " " . $declaracaoImportacao->conhecimentoCargaEmbarqueLocal .  "";
$conhecimentoCargaId                = " " . $declaracaoImportacao->conhecimentoCargaId .  "";
$conhecimentoCargaTipoCodigo        = " " . $declaracaoImportacao->conhecimentoCargaTipoCodigo .  "";
$conhecimentoCargaTipoNome          = " " . $declaracaoImportacao->conhecimentoCargaTipoNome .  "";
$conhecimentoCargaUtilizacao        = " " . $declaracaoImportacao->conhecimentoCargaUtilizacao .  "";
$conhecimentoCargaUtilizacaoNome    = " " . $declaracaoImportacao->conhecimentoCargaUtilizacaoNome .  "";
$dataDesembaraco                    = " " . $declaracaoImportacao->dataDesembaraco .  "";
$dataRegistro                       = " " . $declaracaoImportacao->dataRegistro .  "";
$documentoChegadaCargaCodigoTipo    = " " . $declaracaoImportacao->documentoChegadaCargaCodigoTipo .  "";
$documentoChegadaCargaNome          = " " . $declaracaoImportacao->documentoChegadaCargaNome .  "";
$documentoChegadaCargaNumero        = " " . $declaracaoImportacao->documentoChegadaCargaNumero .  "";

$freteCollect                       = " " . $declaracaoImportacao->freteCollect .  "";
$freteEmTerritorioNacional          = " " . $declaracaoImportacao->freteEmTerritorioNacional .  "";
$freteMoedaNegociadaCodigo          = " " . $declaracaoImportacao->freteMoedaNegociadaCodigo .  "";
$freteMoedaNegociadaNome            = " " . $declaracaoImportacao->freteMoedaNegociadaNome .  "";
$fretePrepaid                       = " " . $declaracaoImportacao->fretePrepaid .  "";
$freteTotalDolares                  = " " . $declaracaoImportacao->freteTotalDolares .  "";
$freteTotalMoeda                    = " " . $declaracaoImportacao->freteTotalMoeda .  "";
$freteTotalReais                    = " " . $declaracaoImportacao->freteTotalReais .  "";

$importadorCodigoTipo               = " " . $declaracaoImportacao->importadorCodigoTipo .  ""; #todos os dados do importador
$importadorCpfRepresentanteLegal    = " " . $declaracaoImportacao->importadorCpfRepresentanteLegal .  "";
$importadorEnderecoBairro           = " " . $declaracaoImportacao->importadorEnderecoBairro .  "";
$importadorEnderecoCep              = " " . $declaracaoImportacao->importadorEnderecoCep .  "";
$importadorEnderecoLogradouro       = " " . $declaracaoImportacao->importadorEnderecoLogradouro .  "";
$importadorEnderecoMunicipio        = " " . $declaracaoImportacao->importadorEnderecoMunicipio .  "";
$importadorEnderecoNumero           = " " . $declaracaoImportacao->importadorEnderecoNumero .  "";
$importadorEnderecoUf               = " " . $declaracaoImportacao->importadorEnderecoUf .  "";
$importadorNome                     = " " . $declaracaoImportacao->importadorNome .  "";
$importadorNomeRepresentanteLegal   = " " . $declaracaoImportacao->importadorNomeRepresentanteLegal .  "";
$importadorNumero                   = " " . $declaracaoImportacao->importadorNumero .  "";
$importadorNumeroTelefone           = " " . $declaracaoImportacao->importadorNumeroTelefone .  "";
$informacaoComplementar             = " " . $declaracaoImportacao->informacaoComplementar .  ""; #
$localDescargaTotalDolares          = " " . $declaracaoImportacao->localDescargaTotalDolares .  "";
$localDescargaTotalReais            = " " . $declaracaoImportacao->localDescargaTotalReais .  "";
$localEmbarqueTotalDolares          = " " . $declaracaoImportacao->localEmbarqueTotalDolares .  "";
$localEmbarqueTotalReais            = " " . $declaracaoImportacao->localEmbarqueTotalReais .  "";
$modalidadeDespachoCodigo           = " " . $declaracaoImportacao->modalidadeDespachoCodigo .  "";
$modalidadeDespachoNome             = " " . $declaracaoImportacao->modalidadeDespachoNome .  "";
$quantidadeVolume                   = " " . $declaracaoImportacao->embalagem->quantidadeVolume .  "";

$numeroDI                           = " " . $declaracaoImportacao->numeroDI .  "";
$operacaoFundap                     = " " . $declaracaoImportacao->operacaoFundap .  "";
$nomeEmbalagem                          = " " . $declaracaoImportacao->embalagem->nomeEmbalagem .  "";
$seguroMoedaNegociadaCodigo         = " " . $declaracaoImportacao->seguroMoedaNegociadaCodigo .  "";
$seguroTotalDolares                 = " " . $declaracaoImportacao->seguroTotalDolares .  "";
$seguroTotalMoedaNegociada          = " " . $declaracaoImportacao->seguroTotalMoedaNegociada .  "";
$seguroTotalReais                   = " " . $declaracaoImportacao->seguroTotalReais .  "";
$sequencialRetificacao              = " " . $declaracaoImportacao->sequencialRetificacao .  "";
$situacaoEntregaCarga               = " " . $declaracaoImportacao->situacaoEntregaCarga .  "";
$tipoDeclaracaoCodigo               = " " . $declaracaoImportacao->tipoDeclaracaoCodigo .  "";
$tipoDeclaracaoNome                 = " " . $declaracaoImportacao->tipoDeclaracaoNome .  "";
$totalAdicoes                       = " " . $declaracaoImportacao->totalAdicoes .  "";
$urfDespachoCodigo                  = " " . $declaracaoImportacao->urfDespachoCodigo .  "";
$urfDespachoNome                    = " " . $declaracaoImportacao->urfDespachoNome .  "";
$valorTotalMultaARecolher           = " " . $declaracaoImportacao->valorTotalMultaARecolher .  "";
$valorTotalMultaARecolherAjustado   = " " . $declaracaoImportacao->valorTotalMultaARecolherAjustado .  "";
$viaTransporteCodigo                = " " . $declaracaoImportacao->viaTransporteCodigo .  "";
$viaTransporteMultimodal            = " " . $declaracaoImportacao->viaTransporteMultimodal .  "";
$viaTransporteNome                  = " " . $declaracaoImportacao->viaTransporteNome .  "";
$viaTransporteNomeTransportador     = " " . $declaracaoImportacao->viaTransporteNomeTransportador .  "";
$viaTransportePaisTransportadorCodigo= " " . $declaracaoImportacao->viaTransportePaisTransportadorCodigo .  "";
$viaTransportePaisTransportadorNome = " " . $declaracaoImportacao->viaTransportePaisTransportadorNome .  "";

$codigoTipoDocumentoDespacho0       = " " . $declaracaoImportacao->documentoInstrucaoDespacho[0]->codigoTipoDocumentoDespacho .  "";
$codigoTipoDocumentoDespacho1       = " " . $declaracaoImportacao->documentoInstrucaoDespacho[1]->codigoTipoDocumentoDespacho .  "";
$codigoTipoDocumentoDespacho2       = " " . $declaracaoImportacao->documentoInstrucaoDespacho[2]->codigoTipoDocumentoDespacho .  "";
$nomeDocumentoDespacho0             = " " . $declaracaoImportacao->documentoInstrucaoDespacho[0]->nomeDocumentoDespacho .  "";
$nomeDocumentoDespacho1             = " " . $declaracaoImportacao->documentoInstrucaoDespacho[1]->nomeDocumentoDespacho .  "";
$nomeDocumentoDespacho2             = " " . $declaracaoImportacao->documentoInstrucaoDespacho[2]->nomeDocumentoDespacho .  "";
$numeroDocumentoDespacho0           = " " . $declaracaoImportacao->documentoInstrucaoDespacho[0]->numeroDocumentoDespacho .  "";
$numeroDocumentoDespacho1           = " " . $declaracaoImportacao->documentoInstrucaoDespacho[1]->numeroDocumentoDespacho .  "";
$numeroDocumentoDespacho2           = " " . $declaracaoImportacao->documentoInstrucaoDespacho[2]->numeroDocumentoDespacho .  "";

$dossieDataVinculacao               = " " . $declaracaoImportacao->dossie->dossieDataVinculacao .  "";
$dossieHoraVinculacao               = " " . $declaracaoImportacao->dossie->dossieHoraVinculacao .  "";
$dossieNumero                       = " " . $declaracaoImportacao->dossie->dossieNumero .  "";
$indicadorDossieVazio               = " " . $declaracaoImportacao->dossie->indicadorDossieVazio .  "";

$codigoTipoEmbalagem                = " " . $declaracaoImportacao->embalagem->codigoTipoEmbalagem .  "";
$quantidadeVolume                   = " " . $declaracaoImportacao->embalagem->quantidadeVolume .  "";

$agenciaIcms                        = " " . $declaracaoImportacao->icms->agenciaIcms .  "";
$bancoIcms                          = " " . $declaracaoImportacao->icms->bancoIcms .  "";
$codigoTipoRecolhimentoIcms         = " " . $declaracaoImportacao->icms->codigoTipoRecolhimentoIcms .  "";
$cpfResponsavelRegistro             = " " . $declaracaoImportacao->icms->cpfResponsavelRegistro .  "";
$dataPagamentoIcms                  = " " . $declaracaoImportacao->icms->dataPagamentoIcms .  "";
$horaRegistro                       = " " . $declaracaoImportacao->icms->horaRegistro .  "";
$nomeTipoRecolhimentoIcms           = " " . $declaracaoImportacao->icms->nomeTipoRecolhimentoIcms .  "";
$numeroSequencialIcms               = " " . $declaracaoImportacao->icms->numeroSequencialIcms .  "";
$ufIcms                             = " " . $declaracaoImportacao->icms->ufIcms .  "";
$valorTotalIcms                     = " " . $declaracaoImportacao->icms->valorTotalIcms .  "";

$agenciaPagamento0                  = " " . $declaracaoImportacao->pagamento[0]->agenciaPagamento .  "";
$bancoPagamento0                    = " " . $declaracaoImportacao->pagamento[0]->bancoPagamento .  "";
$codigoReceita0                     = " " . $declaracaoImportacao->pagamento[0]->codigoReceita .  "";
$codigoTipoPagamento0               = " " . $declaracaoImportacao->pagamento[0]->codigoTipoPagamento .  "";
$contaPagamento0                    = " " . $declaracaoImportacao->pagamento[0]->contaPagamento .  "";
$dataPagamento0                     = " " . $declaracaoImportacao->pagamento[0]->dataPagamento .  "";
$nomeTipoPagamento0                 = " " . $declaracaoImportacao->pagamento[0]->nomeTipoPagamento .  "";
$numeroRetificacao0                 = " " . $declaracaoImportacao->pagamento[0]->numeroRetificacao .  "";
$valorJurosEncargos0                = " " . $declaracaoImportacao->pagamento[0]->valorJurosEncargos .  "";
$valorMulta0                        = " " . $declaracaoImportacao->pagamento[0]->valorMulta .  "";
$valorReceita0                      = " " . $declaracaoImportacao->pagamento[0]->valorReceita .  "";
$agenciaPagamento1                  = " " . $declaracaoImportacao->pagamento[1]->agenciaPagamento .  "";
$bancoPagamento1                    = " " . $declaracaoImportacao->pagamento[1]->bancoPagamento .  "";
$codigoReceita1                     = " " . $declaracaoImportacao->pagamento[1]->codigoReceita .  "";
$codigoTipoPagamento1               = " " . $declaracaoImportacao->pagamento[1]->codigoTipoPagamento .  "";
$contaPagamento1                    = " " . $declaracaoImportacao->pagamento[1]->contaPagamento .  "";
$dataPagamento1                     = " " . $declaracaoImportacao->pagamento[1]->dataPagamento .  "";
$nomeTipoPagamento1                 = " " . $declaracaoImportacao->pagamento[1]->nomeTipoPagamento .  "";
$numeroRetificacao1                 = " " . $declaracaoImportacao->pagamento[1]->numeroRetificacao .  "";
$valorJurosEncargos1                = " " . $declaracaoImportacao->pagamento[1]->valorJurosEncargos .  "";
$valorMulta1                        = " " . $declaracaoImportacao->pagamento[1]->valorMulta .  "";
$valorReceita1                      = " " . $declaracaoImportacao->pagamento[1]->valorReceita .  "";
$agenciaPagamento2                  = " " . $declaracaoImportacao->pagamento[2]->agenciaPagamento .  "";
$bancoPagamento2                    = " " . $declaracaoImportacao->pagamento[2]->bancoPagamento .  "";
$codigoReceita2                     = " " . $declaracaoImportacao->pagamento[2]->codigoReceita .  "";
$codigoTipoPagamento2               = " " . $declaracaoImportacao->pagamento[2]->codigoTipoPagamento .  "";
$contaPagamento2                    = " " . $declaracaoImportacao->pagamento[2]->contaPagamento .  "";
$dataPagamento2                     = " " . $declaracaoImportacao->pagamento[2]->dataPagamento .  "";
$nomeTipoPagamento2                 = " " . $declaracaoImportacao->pagamento[2]->nomeTipoPagamento .  "";
$numeroRetificacao2                 = " " . $declaracaoImportacao->pagamento[2]->numeroRetificacao .  "";
$valorJurosEncargos2                = " " . $declaracaoImportacao->pagamento[2]->valorJurosEncargos .  "";
$valorMulta2                        = " " . $declaracaoImportacao->pagamento[2]->valorMulta .  "";
$valorReceita2                      = " " . $declaracaoImportacao->pagamento[2]->valorReceita .  "";
$agenciaPagamento3                  = " " . $declaracaoImportacao->pagamento[2]->agenciaPagamento .  "";
$bancoPagamento3                    = " " . $declaracaoImportacao->pagamento[2]->bancoPagamento .  "";
$codigoReceita3                     = " " . $declaracaoImportacao->pagamento[2]->codigoReceita .  "";
$codigoTipoPagamento3               = " " . $declaracaoImportacao->pagamento[3]->codigoTipoPagamento .  "";
$contaPagamento3                    = " " . $declaracaoImportacao->pagamento[3]->contaPagamento .  "";
$dataPagamento3                     = " " . $declaracaoImportacao->pagamento[3]->dataPagamento .  "";
$nomeTipoPagamento3                 = " " . $declaracaoImportacao->pagamento[3]->nomeTipoPagamento .  "";
$numeroRetificacao3                 = " " . $declaracaoImportacao->pagamento[3]->numeroRetificacao .  "";
$valorJurosEncargos3                = " " . $declaracaoImportacao->pagamento[3]->valorJurosEncargos .  "";
$valorMulta3                        = " " . $declaracaoImportacao->pagamento[3]->valorMulta .  "";
$valorReceita3                      = " " . $declaracaoImportacao->pagamento[3]->valorReceita .  "";
?>

